apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pod-annotate-cert
  namespace: webhook
spec:
  dnsNames:
    - pod-annotate-webhook
    - pod-annotate-webhook.webhook
    - nimitz.webhook.svc
    - pod-annotate-webhook.webhook.svc
    - pod-annotate-webhook.webhook.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: pod-annotate-issuer
  secretName: pod-annotate-webhook-certs
