apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webhook
resources:
  - issuer.yaml
  - webhook.yaml
  - cert.yaml
  - reg.yaml
configMapGenerator:
  - name: nimitz-config
    files:
      - config.yaml